sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: password
  redis:
    host: localhost
    port: 6379
    database: 0   # 选择数据库，默认是0

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEJCbwbYVBPJrk4X7mU
    access-key-secret: m5Fmg2Q4jIvRakp46tcPmXTVA3yypd
    bucket-name: hiccup

  wechat:
    appid: wx6e532b96e3a94fc6
    secret: 82e2cf1a5dafda70a314832be3268de4